export const capacityOptions = [
  'closed-carriage-4-seat',
  'closed-carriage-6-seat',
  'open-carriage-2-seat',
  'open-carriage-4-seat',
  'ruth-carriage-4-seat',
  'semi-open-carriage-2-seat',
  'semi-open-carriage-4-seat',
]

export const ticketTypes = [
  'ravenglass-adult',
  'ravenglass-child',
  'ravenglass-under3',
  'ravenglass-single-family',
  'ravenglass-four-adults',
  'ravenglass-accessible-adult',
  'ravenglass-accessible-child',
  'ravenglass-accessible-family',
  'ravenglass-dog	',
]

export const ids = [
  'Carriage_A_Seats_1-6',
  'Carriage_A_Seats_7-10',
  'Carriage_A_Seats_11-14',
  'Carriage_A_Seats_15-20',
  'Carriage_B_Seats_1-6',
  'Carriage_B_Seats_7-10',
  'Carriage_B_Seats_11-14',
  'Carriage_B_Seats_15-20',
  'Carriage_C_Seats_1-2',
  'Carriage_C_Seats_3-6',
  'Carriage_C_Seats_7-10',
  'Carriage_C_Seats_11-14',
  'Carriage_C_Seats_15-18',
  'Carriage_C_Seats_19-20',
  'Carriage_D_Seats_1-2',
  'Carriage_D_Seats_3-6',
  'Carriage_D_Seats_7-10',
  'Carriage_D_Seats_11-14',
  'Carriage_D_Seats_15-18',
  'Carriage_E_Seats_1-6',
  'Carriage_E_Seats_7-10',
  'Carriage_E_Seats_11-14',
  'Carriage_F',
  'Carriage_G_Seats_1-2',
  'Carriage_G_Seats_3-6',
  'Carriage_G_Seats_7-10',
  'Carriage_G_Seats_11-14',
  'Carriage_G_Seats_15-18',
  'Carriage_G_Seats_19-20',
  'Carriage_H_Seats_1-2',
  'Carriage_H_Seats_3-6',
  'Carriage_H_Seats_7-10',
  'Carriage_H_Seats_11-14',
  'Carriage_H_Seats_15-18',
  'Carriage_H_Seats_19-20',
  'Joan_Seats_1-4',
  'Joan_Seats_5-8',
  'Joan_Seats_1',
  'Joan_Seats_5',
  'Joan_Seat_9',
  'Joan_Seat_10',
  'Joan_Seat_11',
  'Joan_Seat_12',
  'Joan_Seat_13',
  'Joan_Seat_14',
  'Joan_Seat_66',
]

export const names = [
  'Closed carriage 6-seat compartment',
  'Closed carriage 4-seat compartment',
  'Open carriage 2-seat compartment',
  'Open carriage 4-seat compartment',
  'Accessible carriage',
  'Semi-open 2-seat compartment',
  'Semi-open 4-seat compartment',
  'No 140 First Class seat',
]

export const capacityAllocationIds = [
  {
    id: 'Carriage_A_Seats_1-6',
    name: 1,
  },
]
